version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mekom_kavua
    ports: ["5432:5432"]
    volumes: ["db_data:/var/lib/postgresql/data"]

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: ["8080:80"]
    depends_on: [db]
volumes:
  db_data: