name: Build Yarn Cache
on: workflow_dispatch          # תריץ ידנית פעם אחת
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable && yarn install --immutable
      - run: tar -czf yarn-cache.tgz .yarn .pnp.cjs
      - uses: actions/upload-artifact@v4
        with:
          name: yarn-cache
          path: yarn-cache.tgz
